### ISSUE TITLE
フロントの簡単な要件定義(藤村の真似)

### ISSUE THREAD

**Issue by reibomaru** [team-azb/route-bucket-frontend#1]
フロントの要件ざっくり
- 地図上にマーカーを押すとその地点と経路の末尾との自転車での経路が表示され、ルートが作れる
- 作成した(している)ルートの標高グラフを表示する
- 作成したルートをGPXファイルでダウンロードする
- ルート作成が戻ったり、進んだりできる

**Comment by shugo256** [comment]
細かい&優先度低いと思うけど、点を打つときに道にそうモードとただの直線モードがあると、道なのにまた判定されない時とかに便利だと思う
