### ISSUE TITLE
ローカルでのルート作成機能の基本部分を作る

### ISSUE THREAD

**Issue by reibomaru** [team-azb/route-bucket-frontend#4]
### ざっくり要件
- ルート作成モードとそれ以外を切り替える
- ルート作成モードの時は地図をクリックできる
- ルート作成モード
- 地図をクリックするとその地点がルートに追加される
- 現時点までのルートが画面に表示される
- 地点間での経路の補間はまだやらない
- 進むボタンと戻るボタンでルートの作成を戻ることができる
- クリアボタンで作成したルートが全て消える
- 保存ボタンを押下すると名前を入力してルートが作成される

### 追加のルート作成履歴保存機能
- ルートを追加するたびに非同期でルートデータをバックエンドに送信
- ブラウザを閉じて再度ルート作成モードを押したときに、履歴データがあるならその状態から再開できるoption

**Comment by shugo256** [comment]
これローカルで点の追加/削除/クリアしつつ、その度に裏でasyncでバックエンド叩いて履歴データDBにも入れとくとかどうすか？
そうすると常に状態が保存される & いったん閉じて再開する時も進む/戻るが有効化できる

**Comment by reibomaru** [comment]
なるほど。確かにあったら便利だ。
履歴用のテーブル作って、そこにデータ追加するのと、とってくる感じだよね？

**Comment by shugo256** [comment]
イメージとしては
* `routes/{id}/`以下`PUT`で`add_point`, `delete_point`, `clear`, `forward`,`backward`があって、それらを叩くと履歴の保存 & ルートの保存が行われる
* `GET routes/{id}/`でコース情報と履歴が取得できる
  * 履歴だけ別のエンドポイントでもいいけど

というのを考えてた

**Comment by shugo256** [comment]
ひとまずこのissue的にはローカルでの話だから関係ない & バックエンド書いてから言えやって感じだけど

あとエンドポイント名はまだ適当

**Comment by reibomaru** [comment]
おけおけ、じゃあとりあえず非同期でルートの作成中にデータのやり取りするってのを前提にローカルの実装進めてくわ。
ちなみに、戻ると進むを履歴に保存するってどういうイメージ？
- 間違えたルート作った時に戻るで前に戻れる(undo)
- 進むはundoに対するredo
ってイメージでいたから、DBに保存する必要あるんかな？って気もしてるけど

**Comment by shugo256** [comment]
操作列と今その列のどこにいるかを持っておくと、次使う時も戻る進むが使えるようになるんよね

例えば行った操作が順に add, add, delete, add, undo, undo, redo だと、DBには
* add, add, delete, add という操作列
* 今は3つめのdeleteの後だよという情報

がはいる感じかな
そうすると改めて開き直した時にredoボタン押すとちゃんと最後のaddが実行される

**Comment by reibomaru** [comment]
おっけ、redoの部分までちゃんと再現するって感じなのかどうかを確認できたので、理解したわ

**Comment by shugo256** [comment]
あとclearのundoを実現するには操作列持ってないといかんくて、操作列は多分フロントもバックも持ってると仕様追加するときに両方いじる必要があって辛いから、↑みたいに操作列もDBで管理するのであれば、最終的には各操作後の状態もバックが出力する（フロントでは計算しない）形の方がいい気がする（そうすると非同期じゃなくなるが）
フロントがadd_point, delete_point, clear, redo,undo を要請するとレスポンスで新しいルートの状態が帰ってくる的な

あるいは操作のたびに非同期で`PUT routes/{id}`か何かでフロントで計算されたコース情報と履歴の保存だけ行うようにするか

**Comment by reibomaru** [comment]
> 最終的には各操作後の状態もバックが出力する（フロントでは計算しない）形の方がいい  

これでも全然いいと思うけど、同期させた時にどれくらい処理に時間かかるかが問題だな。。。

>操作のたびに非同期でPUT routes/{id}か何かでフロントで計算されたコース情報と履歴の保存だけ行うようにするか  

これだけでも機能的には十分だと思う。ユーザーが誤ってブラウザ閉じても前回の状態に復元できるって点で。

**Comment by shugo256** [comment]
操作列が長くなってきた時に、サーバーでのRust + 通信とブラウザでのTypeScriptのどっちが速いかが問題だな
これは多分やってみないとわかんなそうだしとりあえずどっちにも舵切れるように、操作ごとにエンドポイント分ける形で行くわ
> routes/{id}/以下PUTでadd_point, delete_point, clear, forward,backwardがあって、それらを叩くと履歴の保存 & ルートの更新/保存が行われる

の形にすることにして、あとで保存だけするのか処理までしてレスポンスも返すのかを比較しよう（動作スピードは大事）
